---
engines:
  rubocop:
    enabled: true
  csslint:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.css"
  - Gemfile.lock
exclude_paths:
- spec_help/dummy/**/*
