require 'xing/spec_helpers/api_response_matchers'
require 'xing/spec_helpers/ci_support'
require 'xing/spec_helpers/dom_equiv'
require 'xing/spec_helpers/json_helpers'
require 'xing/spec_helpers/json_requests'
require 'xing/spec_helpers/routing_spec_patch'
require 'xing/spec_helpers/split_servers'
require 'xing/spec_helpers/test_url_helpers'
